dataloader:
#  imagenet_path: <your_imagenet_path_here>
#  imagenet_path: D:\Code\data\cifar-100
#  imagenet_path: E:\LY\data\cat_vs_dog\train
  img_dir: D:\Code\data\sewage\small_dataset\small_img
  mask_dir: D:\Code\data\sewage\small_dataset\small_label
  num_workers: 8
  batch_size: 4
  train_shuffle: True
  validation_shuffle: False
  pin_memory: True
  img_shape:
    - 768
    - 1024

# training hyperparams
epochs: 2
learning_rate: 0.0001
momentum: 0.9
weight_decay: 0.00001 # 1e-4

optimizer: adam # must be either sgd or adam

# lr scheduling
lr_scheduler:
  type: cosine
  min_lr: 1.e-6

skip_initial_validation: True
output_path: ../output/hrnet

# model architecture
model:
  arch: custom
  model_path: D:\Code\HRNet-Semantic-Segmentation\tools\output\sewage\seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484\best_model.pth

  compression_parameters:
    ignored_modules:
      # list of layer names that you do not want to compress.
      # We follow Stock et al. "And the bit goes down: revisiting the quantization of deep neural networks", ICLR 2020
      # and do not compress the first 7x7 convolutional layer, as it represents only 0.1-0.05% of the network weights
      - conv1
      - ocr_distri_head.object_context_block.f_object.0
      - ocr_distri_head.object_context_block.f_down.0
      - ocr_distri_head.object_context_block.f_pixel.0
      - ocr_distri_head.object_context_block.f_up.0

    k: 256
    fc_subvector_size: 4 # d_fc
    pw_subvector_size: 4 # d_pw
    # Small or large block compression regime for convolutional layers
    large_subvectors: False
    k_means_type: src # kmeans, kmedians, src, slow_src
    k_means_n_iters: 10

    # Used to overwrite configs
    layer_specs:
      fc:
        k: 2048 # Same as BGD
        k_means_type: src

  use_permutations: True
  sls_iterations: 10_000     #test哈哈哈

  permutations:   # parent-children relationships for permutation optimization
    -
      - parents: [conv2, bn2]
      - children: [layer1.0.conv1, layer1.0.downsample.0]
    -
      - parents: [layer1.0.conv2, layer1.0.bn2]
      - children: [layer1.0.conv3]
    -
      - parents: [layer1.0.conv3, layer1.0.bn3, layer1.0.downsample.0, layer1.0.downsample.1,
                  layer1.1.conv3, layer1.1.bn3, layer1.1.conv3, layer1.1.bn3,
                  layer1.2.conv3, layer1.2.bn3, layer1.3.conv3, layer1.3.bn3
      ]
      - children: [layer1.1.conv1, layer1.2.conv1, layer1.3.conv1, transition1.0.0, transition1.1.0.0
      ]
    -
      - parents: [layer1.1.conv2, layer1.1.bn2]
      - children: [layer1.1.conv3]
    -
      - parents: [layer1.2.conv2, layer1.2.bn2]
      - children: [layer1.2.conv3]
    -
      - parents: [layer1.3.conv2, layer1.3.bn2]
      - children: [layer1.3.conv3]
    -
      - parents: [stage2.0.branches.1.3.conv2, stage2.0.branches.1.3.bn2,
                  stage2.0.branches.1.2.conv2, stage2.0.branches.1.2.bn2,
                  stage2.0.branches.1.1.conv2, stage2.0.branches.1.1.bn2,
                  stage2.0.branches.1.0.conv2, stage2.0.branches.1.0.bn2,
                  transition1.1.0.0, transition1.1.0.1,
                  stage2.0.fuse_layers.1.0.0.0, stage2.0.fuse_layers.1.0.0.1,
                  stage3.0.branches.1.0.conv2, stage3.0.branches.1.0.bn2,
                  stage3.0.branches.1.1.conv2, stage3.0.branches.1.1.bn2,
                  stage3.0.branches.1.2.conv2, stage3.0.branches.1.2.bn2,
                  stage3.0.branches.1.3.conv2, stage3.0.branches.1.3.bn2,
                  stage3.0.fuse_layers.1.0.0.0, stage3.0.fuse_layers.1.0.0.1,
                  stage3.0.fuse_layers.1.2.0, stage3.0.fuse_layers.1.2.1,
                  stage4.0.branches.1.0.conv2, stage4.0.branches.1.0.bn2,
                  stage4.0.branches.1.1.conv2, stage4.0.branches.1.1.bn2,
                  stage4.0.branches.1.2.conv2, stage4.0.branches.1.2.bn2,
                  stage4.0.branches.1.3.conv2, stage4.0.branches.1.3.bn2,
                  stage4.0.fuse_layers.1.0.0.0, stage4.0.fuse_layers.1.0.0.1,
                  stage4.0.fuse_layers.1.2.0, stage4.0.fuse_layers.1.2.1,
                  stage4.0.fuse_layers.1.3.0, stage4.0.fuse_layers.1.3.1,
#                  stage4.0.branches.0.3.conv2, stage4.0.branches.0.3.bn2,
#                  stage4.0.branches.0.2.conv2, stage4.0.branches.0.2.bn2,
#                  stage4.0.branches.0.1.conv2, stage4.0.branches.0.1.bn2,
#                  stage4.0.branches.0.0.conv2, stage4.0.branches.0.0.bn2,
#                  stage3.0.fuse_layers.0.1.0, stage3.0.fuse_layers.0.1.1,
#                  stage3.0.fuse_layers.0.2.0, stage3.0.fuse_layers.0.2.1,
#                  stage3.0.branches.0.3.conv2, stage3.0.branches.0.3.bn2,
#                  stage3.0.branches.0.2.conv2, stage3.0.branches.0.2.bn2,
#                  stage3.0.branches.0.1.conv2, stage3.0.branches.0.1.bn2,
#                  stage3.0.branches.0.0.conv2, stage3.0.branches.0.0.bn2,
#                  stage2.0.fuse_layers.0.1.0, stage2.0.fuse_layers.0.1.1,
#                  stage2.0.branches.0.3.conv2, stage2.0.branches.0.3.bn2,
#                  stage2.0.branches.0.2.conv2, stage2.0.branches.0.2.bn2,
#                  stage2.0.branches.0.1.conv2, stage2.0.branches.0.1.bn2,
#                  stage2.0.branches.0.0.conv2, stage2.0.branches.0.0.bn2,
#                  transition1.0.0, transition1.0.1
      ]
      - children: [stage2.0.fuse_layers.0.1.0, stage2.0.branches.1.0.conv1, stage2.0.branches.1.1.conv1,
                   stage2.0.branches.1.2.conv1, stage2.0.branches.1.3.conv1, stage3.0.branches.1.0.conv1,
                   transition2.2.0.0, stage3.0.branches.1.1.conv1, stage3.0.branches.1.2.conv1,
                   stage3.0.branches.1.3.conv1, stage3.0.fuse_layers.0.1.0, stage3.0.fuse_layers.2.1.0.0,
                   stage4.0.branches.1.0.conv1, stage4.0.branches.1.1.conv1, stage4.0.branches.1.2.conv1,
                   stage4.0.branches.1.3.conv1, stage4.0.fuse_layers.0.1.0, stage4.0.fuse_layers.2.1.0.0,
                   stage4.0.fuse_layers.3.1.0.0, overconv.1.0
#                   stage4.0.fuse_layers.1.0.0.0, stage2.0.branches.0.0.conv1
#                   stage4.0.fuse_layers.2.0.0.0, stage4.0.fuse_layers.3.0.0.0, stage4.0.branches.0.3.conv1,
#                   stage4.0.branches.0.2.conv1, stage4.0.branches.0.1.conv1, stage4.0.branches.0.0.conv1,
#                   stage3.0.fuse_layers.1.0.0.0, stage3.0.branches.0.3.conv1, stage3.0.fuse_layers.2.0.0.0,
#                   stage3.0.branches.0.2.conv1, stage3.0.branches.0.1.conv1, stage3.0.branches.0.0.conv1,
#                   stage2.0.fuse_layers.1.0.0.0, stage2.0.branches.0.3.conv1, stage2.0.branches.0.2.conv1,
#                   stage2.0.branches.0.1.conv1
      ]
    -
      - parents: [transition2.2.0.0, transition2.2.0.1,
                  stage3.0.branches.2.0.conv2, stage3.0.branches.2.0.bn2,
                  stage3.0.branches.2.1.conv2, stage3.0.branches.2.1.bn2,
                  stage3.0.branches.2.2.conv2, stage3.0.branches.2.2.bn2,
                  stage3.0.branches.2.3.conv2, stage3.0.branches.2.3.bn2,
                  stage3.0.fuse_layers.2.1.0.0, stage3.0.fuse_layers.2.1.0.1,
                  stage3.0.fuse_layers.2.0.1.0, stage3.0.fuse_layers.2.0.1.1,
                  stage4.0.branches.2.0.conv2, stage4.0.branches.2.0.bn2,
                  stage4.0.branches.2.1.conv2, stage4.0.branches.2.1.bn2,
                  stage4.0.branches.2.2.conv2, stage4.0.branches.2.2.bn2,
                  stage4.0.branches.2.3.conv2, stage4.0.branches.2.3.bn2,
                  stage4.0.fuse_layers.2.0.1.0, stage4.0.fuse_layers.2.0.1.1,
                  stage4.0.fuse_layers.2.1.0.0, stage4.0.fuse_layers.2.1.0.1,
                  stage4.0.fuse_layers.2.3.0, stage4.0.fuse_layers.2.3.1
      ]
      - children: [stage3.0.fuse_layers.0.2.0, stage3.0.fuse_layers.1.2.0, stage3.0.branches.2.0.conv1,
                   stage3.0.branches.2.1.conv1, stage3.0.branches.2.2.conv1, stage3.0.branches.2.3.conv1,
                   transition3.3.0.0, stage4.0.branches.2.0.conv1, stage4.0.branches.2.1.conv1,
                   stage4.0.branches.2.2.conv1, stage4.0.branches.2.3.conv1, stage4.0.fuse_layers.0.2.0,
                   stage4.0.fuse_layers.1.2.0, stage4.0.fuse_layers.3.2.0.0, overconv.2.0
      ]
    -
      - parents: [transition3.3.0.0, transition3.3.0.1,
                  stage4.0.branches.3.0.conv2, stage4.0.branches.3.0.bn2,
                  stage4.0.branches.3.1.conv2, stage4.0.branches.3.1.bn2,
                  stage4.0.branches.3.2.conv2, stage4.0.branches.3.2.bn2,
                  stage4.0.branches.3.3.conv2, stage4.0.branches.3.3.bn2,
                  stage4.0.fuse_layers.3.0.2.0, stage4.0.fuse_layers.3.0.2.1,
                  stage4.0.fuse_layers.3.1.1.0, stage4.0.fuse_layers.3.1.1.1,
                  stage4.0.fuse_layers.3.2.0.0, stage4.0.fuse_layers.3.2.0.1
      ]
      - children: [stage4.0.fuse_layers.0.3.0, stage4.0.fuse_layers.1.3.0, stage4.0.fuse_layers.2.3.0,
                   stage4.0.branches.3.0.conv1, stage4.0.branches.3.1.conv1, stage4.0.branches.3.2.conv1,
                   stage4.0.branches.3.3.conv1,  overconv.3.0
      ]
    -
      - parents: [aux_conv.0, aux_conv.1]
      - children: [aux_head.0]
    -
      - parents: [aux_head.0]
      - children: [aux_head.3]
    -
      - parents: [ocr_distri_head.object_context_block.f_object.0,
                  ocr_distri_head.object_context_block.f_object.1.0
      ]
      - children: [ocr_distri_head.object_context_block.f_object.2]
    -
      - parents: [ocr_distri_head.object_context_block.f_pixel.0,
                  ocr_distri_head.object_context_block.f_pixel.1.0]
      - children: [ocr_distri_head.object_context_block.f_pixel.2]
    -
      - parents: [ocr_distri_head.conv_bn_dropout.0, ocr_distri_head.conv_bn_dropout.1.0]
      - children: [cls_head]